## Основы pytorch

Для выполнения ДЗ создайте приватный репозиторий и добавьте `https://github.com/norsage` в collaborators (Settings -> Collaborators -> Add people)

In [1]:
import torch

#### 1. Операции над тензорами (1 балл)

##### 1.1 Среднее значение по столбцам

In [2]:
torch.manual_seed(42)
x = torch.randint(10, size=(2, 3)).float()
x

tensor([[2., 7., 6.],
        [4., 6., 5.]])

In [3]:
mean_by_row = x.mean(dim=0)
assert torch.allclose(
    mean_by_row, _expected := torch.tensor([3.0, 6.5, 5.5])
), f"{mean_by_row} != {_expected}"

##### 1.2. Взвешенное среднее
В тензоре `w` находятся ненормализованные веса для расчёта взвешенных средних тензора `x` по строкам.

Найдите эти взвешенные средние, получая нормализованные веса с помощью функции `torch.softmax` (или метода `.softmax`)

In [4]:
torch.manual_seed(42)
x = torch.randint(10, size=(2, 3)).float()
w = torch.randint(10, size=(2, 3)).float()
print(x)
print(w)

tensor([[2., 7., 6.],
        [4., 6., 5.]])
tensor([[0., 4., 0.],
        [3., 8., 4.]])


In [5]:
w_avg = (x * torch.softmax(w, dim=1)).sum(dim=1)
assert torch.allclose(
    w_avg, _expected := torch.tensor([6.8940, 5.9690])
), f"{w_avg} != {_expected}"

##### 1.3. Умножение матриц на векторы

В тензоре `m` - две матрицы, нужно сделать тензор, в котором i-й элемент - результат умножения матрицы `m[i]` на вектор `x[i]`.

Это можно было бы сделать так: `torch.stack([m[i] @ x[i] for i in len(m)])`.

Попробуйте найти решение без цикла.

In [6]:
torch.manual_seed(42)
x = torch.randint(10, size=(2, 3)).float()
m = torch.randint(10, size=(2, 3, 3)).float()
print(m)
print(x)

tensor([[[0., 4., 0.],
         [3., 8., 4.],
         [0., 4., 1.]],

        [[2., 5., 5.],
         [7., 6., 9.],
         [6., 3., 1.]]])
tensor([[2., 7., 6.],
        [4., 6., 5.]])


In [7]:
matmul = torch.bmm(m, x.view(2, 3, 1)).view(2, 3)
assert torch.allclose(
    matmul, _expected := torch.tensor([[28.0, 86.0, 34.0], [63.0, 109.0, 47.0]])
), f"{matmul} != {_expected}"

##### 1.4. Матрица попарных расстояний

Даны две матрицы `x` и `y`, нужно получить матрицу `d`, где `d[i, j]` - евклидово расстояние между векторами `x[i]` и `y[j]`.

Подсказка 1: воспользуйтесь broadcasting и добавлением размерностей в исходные тензоры.

Подсказка 2: можно не считать евклидово расстояние вручную, есть функция `torch.linalg.norm`



In [8]:
torch.manual_seed(42)
x = torch.randint(10, size=(2, 3)).float()
y = torch.randint(10, size=(3, 3)).float()
print(x)
print(y)

tensor([[2., 7., 6.],
        [4., 6., 5.]])
tensor([[0., 4., 0.],
        [3., 8., 4.],
        [0., 4., 1.]])


In [9]:
pdist = torch.linalg.norm(x.unsqueeze(1) - y.unsqueeze(0), dim=2)
assert torch.allclose(
    pdist,
    _expected := torch.tensor([[7.0000, 2.4495, 6.1644], [6.7082, 2.4495, 6.0000]]),
), f"{pdist} != {_expected}"

#### 2. Функция Power (1 балл)
Используя сложение и умножение, реализуйте возведение в целочисленную степень FloatTensor как функцию autograd (т.е. наследника `torch.autograd.Function`)

In [10]:
class Power(torch.autograd.Function):
    @staticmethod
    def forward(tensor, p):
        return tensor ** p

    @staticmethod
    def setup_context(ctx, inputs, output):
        ctx.first, ctx.second = inputs

    @staticmethod
    def backward(ctx, grad_output):
        tensor, p = ctx.first, ctx.second
        grad_tensor = grad_output * p * (tensor ** (p - 1))
        return grad_tensor, None

In [11]:
assert torch.all(Power.apply(torch.tensor([1, 2, 3]), 0) == torch.tensor([1, 1, 1]))
assert torch.all(Power.apply(torch.tensor([1, 2, 3]), 2) == torch.tensor([1, 4, 9]))

    #### 3. Многочлен (3 балла)
Найдите корень (он один) заданного полинома (очень хорошего!) с точностью до пяти знаков после запятой:
1. Используя бинарный поиск https://en.wikipedia.org/wiki/Binary_search_algorithm
2. Используя метод Ньютона https://en.wikipedia.org/wiki/Newton%27s_method
   
   Задаётся начальное приближение вблизи предположительного корня, после чего строится касательная к графику исследуемой функции в точке приближения, для которой находится пересечение с осью абсцисс. Эта точка берётся в качестве следующего приближения. И так далее, пока не будет достигнута необходимая точность.
   
   (hint: для вычисления производных используйте метод `backward()`)
   
   $x_{n+1} = x_{n} - \frac{f(x_n)}{f'(x_n)}$

Сравните скорость методов с помощью `%%timeit`, т.е. оцените, какой из них найдёт ответ быстрее

In [12]:
from typing import Callable

Polynomial = Callable[[torch.FloatTensor], torch.FloatTensor]


def poly(x: torch.FloatTensor) -> torch.FloatTensor:
    return x**7 + 5 * x**3 + 17 * x - 9

In [13]:
torch.set_printoptions(precision=5)

def bin_search_find_zero(poly: Polynomial) -> torch.FloatTensor:
    
    left = torch.tensor(0., dtype=torch.float64)
    right = torch.tensor(1., dtype=torch.float64)
    epsilon = torch.tensor(1e-5, dtype=torch.float64)
    
    while right - left > epsilon:
        mid = (left + right) / 2
        mid_value = poly(mid)
        if mid_value * poly(left) < 0:
            right = mid
        else:
            left = mid
            
    return (left + right) / 2

print(bin_search_find_zero(poly))

tensor(0.49362, dtype=torch.float64)


In [14]:
def newton_find_zero(poly: Polynomial) -> torch.FloatTensor:
    """Функция для метода Ньютона"""

    # первое приближение (не забываем про то, что понадобится градиент!)
    x = torch.tensor(1.0, requires_grad=True, dtype=torch.float64)
    x_old = torch.tensor(2.0, dtype=torch.float64)

    # останавливаемся, если значение функции достаточно близко к нулю
    tol = 10**-5

    # значение
    val = poly(x)

    # цикл обновления
    while abs(x - x_old) > tol:
        val.backward()
        f_dx = x.grad  # производная 
        x_old = x  # сохраняем старый x
        with torch.no_grad():
            x = x - val / f_dx  # пересчитываем x
        x = x.requires_grad_(True)
        val = poly(x)  # вычисляем новое значение
        
    # еще вроде работает такой вариант
    '''
    while abs(x - x_old) > tol:
        val.backward()
        f_dx = x.grad
        x_old = x
        x = x - val / f_dx
        x = x.detach().requires_grad_(True)
        val = poly(x)
    '''

    return x

In [15]:
x = newton_find_zero(poly)
print(x)
print(poly(x))

tensor(0.49362, dtype=torch.float64, requires_grad=True)
tensor(1.77636e-15, dtype=torch.float64, grad_fn=<SubBackward0>)


In [16]:
%%timeit
x = newton_find_zero(poly)

855 μs ± 19.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
%%timeit
y = bin_search_find_zero(poly)

1.39 ms ± 21.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


То есть быстрее работает метод Ньютона